# Generated by Django 4.2.2 on 2023-07-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%y/%m/%d/")),
                ("facebook_link", models.URLField(max_length=100)),
                ("twitter_link", models.URLField(max_length=100)),
                ("google_plus_link", models.URLField(max_length=100)),
                ("created_data", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
